# Generated by Django 6.0.1 on 2026-01-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='slag',
            new_name='slug',
        ),
    ]
